name: flutter_training
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

scripts:
  build_web: flutter build web --release
  create_web_folder: mkdir docs
  # create_web_files: xcopy -r build/web/* docs/
  create_web_files: xcopy /E /H /Y build\web\* docs\
